In [13]:
# from a group claim id (qurey id) this returns me the gene_id that i can take a look at dictybase. Makes my life easier.

In [4]:
import polars as pl
claim_cleaned_pmid_nonNA_abstract=pl.read_parquet("../output/cleaned/claim_cleaned_long_pmids_nonNA_abstract.parquet")

In [6]:
claim_cleaned_pmid_nonNA_abstract

shape: (2_561, 11)
┌──────────┬─────────────┬────────────┬────────────┬───┬──────┬──────────┬────────────┬────────────┐
│ claim_id ┆ claim_plain ┆ anchors    ┆ publicatio ┆ … ┆ year ┆ pmid     ┆ title      ┆ abstract_c │
│ ---      ┆ ---         ┆ ---        ┆ n_id       ┆   ┆ ---  ┆ ---      ┆ ---        ┆ lean       │
│ i64      ┆ str         ┆ list[struc ┆ ---        ┆   ┆ i32  ┆ str      ┆ str        ┆ ---        │
│          ┆             ┆ t[2]]      ┆ i64        ┆   ┆      ┆          ┆            ┆ str        │
╞══════════╪═════════════╪════════════╪════════════╪═══╪══════╪══════════╪════════════╪════════════╡
│ 1878     ┆ These       ┆ [{175,[162 ┆ 16288      ┆ … ┆ 2017 ┆ 28413119 ┆ The two    ┆ Autophagy  │
│          ┆ results     ┆ 88]}]      ┆            ┆   ┆      ┆          ┆ Dictyostel ┆ is a       │
│          ┆ suggest     ┆            ┆            ┆   ┆      ┆          ┆ ium        ┆ highly     │
│          ┆ that Atg…   ┆            ┆            ┆   ┆      ┆          ┆ discoide…  ┆ conserve…  │
│ 403      ┆ Disruption  ┆ [{103,[663 ┆ 6630       ┆ … ┆ 1989 ┆ 2515990  ┆ Selective  ┆ The        │
│          ┆ of csaA     ┆ 0]}]       ┆            ┆   ┆      ┆          ┆ eliminatio ┆ contact    │
│          ┆ results in  ┆            ┆            ┆   ┆      ┆          ┆ n of the   ┆ site A gly │
│          ┆ …           ┆            ┆            ┆   ┆      ┆          ┆ c…         ┆ coprotei…  │
│ 1105     ┆ MyoB is non ┆ [{163,[660 ┆ 12097      ┆ … ┆ 2012 ┆ 22367211 ┆ Molecular  ┆ Class I    │
│          ┆ -filamentou ┆ 8]}, {164, ┆            ┆   ┆      ┆          ┆ basis of   ┆ myosins    │
│          ┆ s and co…   ┆ [6857]},   ┆            ┆   ┆      ┆          ┆ dynamic    ┆ have a     │
│          ┆             ┆ {…         ┆            ┆   ┆      ┆          ┆ rel…       ┆ single …   │
│ 1196     ┆ pestis      ┆ [{235,[171 ┆ 17146      ┆ … ┆ 2018 ┆ 29350155 ┆ Yersinia   ┆ Plague     │
│          ┆ recruits    ┆ 46]}]      ┆            ┆   ┆      ┆          ┆ pestis     ┆ ecology is │
│          ┆ host Rab1B  ┆            ┆            ┆   ┆      ┆          ┆ Survival   ┆ characteri │
│          ┆ pro…        ┆            ┆            ┆   ┆      ┆          ┆ and R…     ┆ ze…        │
│ 582      ┆ FspA        ┆ [{122,[135 ┆ 13550      ┆ … ┆ 2013 ┆ 24128258 ┆ Two        ┆ Recognitio │
│          ┆ protein is  ┆ 50]}]      ┆            ┆   ┆      ┆          ┆ distinct   ┆ n of       │
│          ┆ an          ┆            ┆            ┆   ┆      ┆          ┆ sensing    ┆ bacteria   │
│          ┆ essential   ┆            ┆            ┆   ┆      ┆          ┆ pathways … ┆ by met…    │
│          ┆ c…          ┆            ┆            ┆   ┆      ┆          ┆            ┆            │
│ …        ┆ …           ┆ …          ┆ …          ┆ … ┆ …    ┆ …        ┆ …          ┆ …          │
│ 439      ┆ Dominant    ┆ [{174,[174 ┆ 17491      ┆ … ┆ 2018 ┆ 29843387 ┆ The Effect ┆ Rab        │
│          ┆ negative    ┆ 91]}]      ┆            ┆   ┆      ┆          ┆ of Overexp ┆ GTPases    │
│          ┆ rabS cells  ┆            ┆            ┆   ┆      ┆          ┆ ressed Dd… ┆ are        │
│          ┆ d…          ┆            ┆            ┆   ┆      ┆          ┆            ┆ essential  │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆            ┆ regu…      │
│ 1309     ┆ Rab2A is    ┆ [{83,[1542 ┆ 17491      ┆ … ┆ 2018 ┆ 29843387 ┆ The Effect ┆ Rab        │
│          ┆ associated  ┆ 2]}, {136, ┆            ┆   ┆      ┆          ┆ of Overexp ┆ GTPases    │
│          ┆ with both … ┆ [17491]}]  ┆            ┆   ┆      ┆          ┆ ressed Dd… ┆ are        │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆            ┆ essential  │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆            ┆ regu…      │
│ 516      ┆ Expression  ┆ [{169,[116 ┆ 11602      ┆ … ┆ 2011 ┆ 21810415 ┆ BzpF is a  ┆ The cAMP   │
│          ┆ of cotE is  ┆ 02]}]      ┆            ┆   ┆      ┆          ┆ CREB-like  ┆ response   │
│          ┆ dependen…   ┆            ┆            ┆   ┆      ┆          ┆ transcript ┆ element-bi │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆ …          ┆ nd…        │
│ 536      ┆ extended    ┆ [{0,[11602 ┆ 11602      ┆ … ┆ 2011 ┆ 21810415 ┆ BzpF is a  ┆ The cAMP   │
│          ┆ these       ┆ ]}]        ┆            ┆   ┆      ┆          ┆ CREB-like  ┆ response   │
│          ┆ findings    ┆            ┆            ┆   ┆      ┆          ┆ transcript ┆ element-bi │
│          ┆ and de…     ┆            ┆            ┆   ┆      ┆          ┆ …          ┆ nd…        │
│ 2040     ┆ When        ┆ [{155,[107 ┆ 1071       ┆ … ┆ 2005 ┆ 15689527 ┆ Evolutiona ┆ In eukaryo │
│          ┆ activity is ┆ 1]}]       ┆            ┆   ┆      ┆          ┆ ry diversi ┆ tes, C5-cy │
│          ┆ observed,   ┆            ┆            ┆   ┆      ┆          ┆ fication   ┆ tosine     │
│          ┆ it …        ┆            ┆            ┆   ┆      ┆          ┆ o…         ┆ met…       │
└──────────┴─────────────┴────────────┴────────────┴───┴──────┴──────────┴────────────┴────────────┘

In [8]:
claim_group_map=pl.read_csv("../output/cleaned/claim_group_map.tsv", separator="\t")

In [9]:
group_gene_map = (
    claim_cleaned_pmid_nonNA_abstract
    .select(["claim_id", "gene_id"])
    .unique()
    .join(claim_group_map, on="claim_id", how="left")
    .group_by("group_claim_id")
    .agg(
        pl.col("gene_id")
          .drop_nulls()
          .unique()
          .sort()
          .alias("gene_ids")
    )
)

In [10]:
group_gene_map

shape: (1_705, 2)
┌────────────────┬─────────────────────────────────┐
│ group_claim_id ┆ gene_ids                        │
│ ---            ┆ ---                             │
│ i64            ┆ list[str]                       │
╞════════════════╪═════════════════════════════════╡
│ 1218           ┆ ["DDB_G0275077"]                │
│ 1209           ┆ ["DDB_G0269364"]                │
│ 545            ┆ ["DDB_G0274605"]                │
│ 170            ┆ ["DDB_G0278739"]                │
│ 953            ┆ ["DDB_G0285793"]                │
│ …              ┆ …                               │
│ 238            ┆ ["DDB_G0288427"]                │
│ 1572           ┆ ["DDB_G0267376"]                │
│ 643            ┆ ["DDB_G0272004"]                │
│ 1411           ┆ ["DDB_G0275323"]                │
│ 122            ┆ ["DDB_G0272562,DDB_G0272756,DD… │
└────────────────┴─────────────────────────────────┘

In [11]:
group_gene_dict = {
    row[0]: row[1]
    for row in group_gene_map.select(["group_claim_id", "gene_ids"]).iter_rows()
}

def get_gene_ids(group_claim_id):
    return group_gene_dict.get(group_claim_id, [])

In [12]:
get_gene_ids(1468)

['DDB_G0284977']

http://dictybase.org/gene/DDB_G0284977

In [14]:
get_gene_ids(1616)

['DDB_G0275451']

In [17]:
get_gene_ids(1005)

['DDB_G0283907']